# Generated by Django 4.2.5 on 2024-08-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='categegory',
            new_name='category',
        ),
    ]
